language: cpp

dist: bionic

compiler:
- gcc

os:
- linux

branches:
    only:
    - master

notifications:
    email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install libboost-test-dev

script:
- autoreconf -f -i
- ./configure CXXFLAGS=--std=c++14
- make

- cd tests
- autoreconf -f -i
- ./configure CXXFLAGS=--std=c++14
- make check

- cd ..
- mkdir build
- cd build
- cmake ..
- cmake --build  .
